#!/usr/bin/env bash
#
# Plays files and STRM files from a playlist
#
# Copyright Â© 2013 Janne Enberg http://lietu.net/
# This work is free. You can redistribute it and/or modify it under the
# terms of the Do What The Fuck You Want To Public License, Version 2,
# as published by Sam Hocevar. See http://www.wtfpl.net/ for more details.
#

set -o nounset
set -o errexit

# A POSIX variable
OPTIND=1         # Reset in case getopts has been used previously in the shell.
verbose=0

# If you want to switch omxplayer to something else, or add parameters, use these
PLAYER="omxplayer"
PLAYER_OPTIONS=""

# Where is the playlist
PLAYLIST_FILE="/var/omxplayer_playlist_player/playlist"


while getopts "h?vf" opt; do
        case "$opt" in
        h|\?) show_help
              exit 0
                ;;
        v) verbose=1
                ;;
        esac
done

shift $((OPTIND-1))

if [ ! -z ${var+x} ]; then
        [ "$1" = "--" ] && shift
fi


if [ ! -z "$@" ]; then
        PLAYLIST_FILE="$@"
fi

if [ "$verbose" = "1" ]; then
        echo "verbose=$verbose, playlist file=$PLAYLIST_FILE, Text: $@"
fi


# Process playlist contents
while [ true ]; do
        # Sleep a bit so its possible to kill this
        sleep 1

        # Do nothing if the playlist doesnt exist
        if [ ! -f "${PLAYLIST_FILE}" ]; then
                echo "Playlist file ${PLAYLIST_FILE} not found"
                continue
        fi

        # Get the top of the playlist
        file=$(cat "${PLAYLIST_FILE}" | head -n1)

        # Skip if this is empty
        if [ -z "${file}" ]; then
                echo "Playlist empty or bumped into an empty entry for some reason"

                cat "${PLAYLIST_FILE}" | tail -n+2 > "${PLAYLIST_FILE}.new"
                echo "$file" >> "${PLAYLIST_FILE}.new"
                mv "${PLAYLIST_FILE}.new" "${PLAYLIST_FILE}"
                continue
        fi

        # Check that the file exists
        if [ ! -f "${file}" ]; then
                echo "Playlist entry ${file} not found"
                continue
        fi

        echo
        echo "Playing ${file} ..."
        echo
        
        stream=$(cat "$file")
        echo
        echo "Stream ${stream} ..."
        echo

        filename=$(basename "$file")
        extension="${filename##*.}"
        filename=${filename%.*}
        echo
        echo "ext ${extension} ..."
        echo
        if [ `echo $extension | tr [:upper:] [:lower:]` =  `echo strm | tr [:upper:] [:lower:]` ]; then
               play=$(cat "$file")
        else
                play=$file
        fi
        echo
        echo "Hi ${file} ..."
        echo

        googletts "Now playing ${filename}"
        "${PLAYER}" ${PLAYER_OPTIONS} "${play}" || true

        echo
        echo "Playback complete, continuing to next item on playlist."
        echo


        # Sleep a bit so its possible to kill this
        sleep 1

        # And strip it off the playlist file
        cat "${PLAYLIST_FILE}" | tail -n+2 > "${PLAYLIST_FILE}.new"
        echo "$file" >> "${PLAYLIST_FILE}.new"
        mv "${PLAYLIST_FILE}.new" "${PLAYLIST_FILE}"

done